// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFRbZqSNUUod2WKKnyBXDSrgONCLdM7z4',
    appId: '1:239117471945:web:c72ce57ef9c93fc2253d18',
    messagingSenderId: '239117471945',
    projectId: 'eatsleepride-bdd5f',
    authDomain: 'eatsleepride-bdd5f.firebaseapp.com',
    storageBucket: 'eatsleepride-bdd5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo7I278QyT2B8D2FRc_j-wWV9Pr7s-430',
    appId: '1:239117471945:android:10fc62765382a3ce253d18',
    messagingSenderId: '239117471945',
    projectId: 'eatsleepride-bdd5f',
    storageBucket: 'eatsleepride-bdd5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-13pHLzUPdvKoUUcjxgZ-MtzUAvVoj3c',
    appId: '1:239117471945:ios:bd9d590d09f548e0253d18',
    messagingSenderId: '239117471945',
    projectId: 'eatsleepride-bdd5f',
    storageBucket: 'eatsleepride-bdd5f.firebasestorage.app',
    iosBundleId: 'com.tlskals.eatsleepride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-13pHLzUPdvKoUUcjxgZ-MtzUAvVoj3c',
    appId: '1:239117471945:ios:2b04f8d73853e9a5253d18',
    messagingSenderId: '239117471945',
    projectId: 'eatsleepride-bdd5f',
    storageBucket: 'eatsleepride-bdd5f.firebasestorage.app',
    iosBundleId: 'com.tlskals.eatsleepride',
  );
}
